#:import images_path kivymd.images_path

# md_bg_color: app.theme_cls.primary_color # Esto es para que se vea el fondo del MDToolbar

<MainScreenView>

    FitImage:
        source: f"{images_path}firebase-logo.png"

    MDBoxLayout:
        orientation: "vertical"

        MDToolbar:
            title: "MainScreen"
            left_action_items: [["food", lambda x: root.set_screen('track screen')]]

        MDFloatLayout:

            MDBoxLayout:
                orientation: "vertical"
                adaptive_height: True
                size_hint_x: None
                width: root.width - dp(72)
                radius: 12
                padding: "12dp"
                md_bg_color: 1, 1, 1, .5
                pos_hint: {"center_x": .5, "center_y": .5}

                MDLabel:
                    id: prev_label
                    text: "Tracking progress"
                    font_style: "H6"
                    adaptive_height: True
                    halign: "center"

                MDBoxLayout:
                    orientation: "vertical"
                    adaptive_height: True
                    padding: "50dp"
                    spacing: "20dp"

                    MDLabel:
                        text: "Proteins"
                        halign: "left"

                    MDProgressBar:
                        id: progress_protein
                        value: 55
                        max: 100
                        orientation: "horizontal"

                    MDBoxLayout:
                        orientation: "vertical"
                        adaptive_height: True
                        spacing: "1dp"

                    MDLabel:
                        text: "Sugars"
                        halign: "left"

                    MDProgressBar:
                        id: progress_sugar
                        value: 55
                        max: 100
                        orientation: "horizontal"

                    MDBoxLayout:
                        orientation: "vertical"
                        adaptive_height: True
                        spacing: "1dp"

                    MDLabel:
                        text: "Grass"
                        halign: "left"

                    MDProgressBar:
                        id: progress_grass
                        value: 55
                        max: 100
                        orientation: "horizontal"

                    MDBoxLayout:
                        orientation: "vertical"
                        adaptive_height: True
                        spacing: "1dp"


    MDFillRoundFlatButton:
        text: "ADD FOOD"
        on_release: root.controller.on_tap_button_login()
        pos_hint: {"center_x": .5, "center_y": .1}
