#:import images_path kivymd.images_path
#:import get_color_from_hex kivy.utils.get_color_from_hex

# md_bg_color: app.theme_cls.primary_color # Esto es para que se vea el fondo del MDToolbar root.set_screen('track screen')

<MainScreenView>

    MDBoxLayout:
        orientation: "vertical"

        MDBoxLayout:
            orientation: "vertical"
            adaptive_height: True
            size_hint_x: None
            width: root.width
            radius: 12
            padding: "12dp"
            md_bg_color: 1, 1, 1, .5
            pos_hint: {"center_x": .5, "center_y": .5}

            MDLabel:
                id: title_label
                text: "   Nutrix - " + root.get_version()
                font_style: "H5"
                adaptive_height: True
                halign: "left"

            MDLabel:
                id: prev_label
                text: "Tracking progress"
                font_style: "H6"
                adaptive_height: True
                halign: "center"
                spacing: "20dp"

            MDBoxLayout:
                orientation: "vertical"
                adaptive_height: True
                padding: "30dp"
                spacing: "30dp"

                MDLabel:
                    text: "Proteins"
                    halign: "left"

                MDProgressBar:
                    id: progress_protein
                    value: 55
                    max: 100
                    orientation: "horizontal"

                MDLabel:
                    text: "Carbohydrate"
                    halign: "left"

                MDProgressBar:
                    id: progress_carbohydrates
                    value: 55
                    max: 100
                    orientation: "horizontal"

                MDLabel:
                    text: "Fats"
                    halign: "left"

                MDProgressBar:
                    id: progress_fats
                    value: 55
                    max: 100
                    orientation: "horizontal"

        MDBottomNavigation:
            panel_color: app.theme_cls.primary_color
            text_color_active: 0, 0, 0, 1

            MDBottomNavigationItem:
                name: 'screen 1'
                text: 'Add Food'
                icon: 'food'
                on_tab_press: root.set_screen('track screen')
