#:import images_path kivymd.images_path
#:import get_color_from_hex kivy.utils.get_color_from_hex

# md_bg_color: app.theme_cls.primary_color # Esto es para que se vea el fondo del MDToolbar root.set_screen('track screen')

<MainScreenView>

    MDBoxLayout:
        orientation: "vertical"

        MDFloatLayout:

            MDBoxLayout:
                orientation: "vertical"
                adaptive_height: True
                size_hint_x: None
                width: root.width - dp(72)
                radius: 12
                padding: "12dp"
                md_bg_color: 1, 1, 1, .5
                pos_hint: {"center_x": .5, "center_y": .5}

                MDLabel:
                    id: prev_label
                    text: "Tracking progress"
                    font_style: "H6"
                    adaptive_height: True
                    halign: "center"

                MDBoxLayout:
                    orientation: "vertical"
                    adaptive_height: True
                    padding: "50dp"
                    spacing: "20dp"

                    MDLabel:
                        text: "Proteins"
                        halign: "left"

                    MDProgressBar:
                        id: progress_protein
                        value: 55
                        max: 100
                        orientation: "horizontal"

                    MDLabel:
                        text: "Sugars"
                        halign: "left"

                    MDProgressBar:
                        id: progress_sugar
                        value: 55
                        max: 100
                        orientation: "horizontal"

                    MDLabel:
                        text: "Grass"
                        halign: "left"

                    MDProgressBar:
                        id: progress_grass
                        value: 55
                        max: 100
                        orientation: "horizontal"

        MDBottomNavigation:
            panel_color: get_color_from_hex("#eeeaea")
            selected_color_background: get_color_from_hex("#97ecf8")
            text_color_active: 0, 0, 0, 1

            MDBottomNavigationItem:
                name: 'screen 1'
                text: 'Mail'
                icon: 'gmail'
                badge_icon: "numeric-10"

                MDLabel:
                    text: 'Mail'
                    halign: 'center'

            MDBottomNavigationItem:
                name: 'screen 2'
                text: 'Discord'
                icon: 'discord'
                badge_icon: "numeric-5"

                MDLabel:
                    text: 'Discord'
                    halign: 'center'

            MDBottomNavigationItem:
                name: 'screen 3'
                text: 'LinkedIN'
                icon: 'linkedin'

                MDLabel:
                    text: 'LinkedIN'
                    halign: 'center'